config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :doctors
  resources :patients do
    resources :journals do
      resources :comments
    end
  end

  root 'welcome#index'
  get '/dlogin' => 'doctor_sessions#new'
  post '/dlogin' => 'doctor_sessions#create'
  get '/dlogout' => 'doctor_sessions#destroy'
  delete '/dlogout' => 'doctor_sessions#destroy'
  get '/plogin' => 'patient_sessions#new'
  post '/plogin' => 'patient_sessions#create'
  get '/plogout' => 'patient_sessions#destroy'
  delete '/plogout' => 'patient_sessions#destroy'
  get '/patients/:id/adddoc' => 'patients#adddoc'
  get '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/add_entry' => 'journals#new'
  get '/deletec' => 'comments#destroy'
  get '/doctors/:id/patients' => 'doctors#patients'
  get '/patients/:id/doctors' => 'patients#doctors'
  patch '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/patientsj/:id' => 'patients#journals'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :journal
  belongs_to :patient
  accepts_nested_attributes_for :patient
  accepts_nested_attributes_for :journal
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_journal
  before_action :set_patient

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.journal = @journal
    respond_to do |format|
      if @comment.save
        format.html { redirect_to("/patients/#{@journal.patient.id}/journals/#{@journal.id}") }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to patient_journal_path(@patient, @journal), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to patient_journal_path(@patient, @journal), notice: 'Comment destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_journal
    @journal = Journal.find(params[:journal_id])
  end

  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:content, :journal_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@patient, @journal, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area(:content, size: "50x10") %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@patient, @journal, @comment] %> |
<%= link_to 'Back', patient_journal_comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Journal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.journal %></td>
        <td><%= link_to 'Show', patient_journal_comment_path(comment.journal.patient, comment.journal, comment) %></td>
        <td><%= link_to 'Edit', edit_patient_journal_comment_path(comment.journal.patient, comment.journal, comment) %></td>
        <td><%= link_to 'Destroy', "/patients/#{comment.journal.patient.id}/journals/#{comment.journal.id}/comments/#{comment.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_patient_journal_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_journal_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Journal:</strong>
  <%= @comment.journal %>
</p>

<%= link_to 'Edit', edit_patient_journal_comment_path([@patient, @journal, @comment]) %> |
<%= link_to 'Back', patient_journal_comment_path %>