config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :doctors
  resources :patients do
    resources :journals do
      resources :comments
    end
  end

  root 'welcome#index'
  get '/dlogin' => 'doctor_sessions#new'
  post '/dlogin' => 'doctor_sessions#create'
  get '/dlogout' => 'doctor_sessions#destroy'
  delete '/dlogout' => 'doctor_sessions#destroy'
  get '/plogin' => 'patient_sessions#new'
  post '/plogin' => 'patient_sessions#create'
  get '/plogout' => 'patient_sessions#destroy'
  delete '/plogout' => 'patient_sessions#destroy'
  get '/patients/:id/adddoc' => 'patients#adddoc'
  get '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/add_entry' => 'journals#new'
  get '/deletec' => 'comments#destroy'
  get '/doctors/:id/patients' => 'doctors#patients'
  get '/patients/:id/doctors' => 'patients#doctors'
  patch '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/patientsj/:id' => 'patients#journals'

end

app/models/patient.rb
require 'bcrypt'

class Patient < ActiveRecord::Base
  include BCrypt
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password_hash, presence: true
  validate :name_capital
  validate :proper_email
  has_many :patients_doctors, dependent: :destroy
  has_many :doctors, through: :patients_doctors
  has_many :journals
  accepts_nested_attributes_for :doctors
  accepts_nested_attributes_for :journals
  has_many :comments, through: :journals
  accepts_nested_attributes_for :comments

  def name_capital
    capital = name =~ /[A-Z]/
    errors.add(:name, 'name is not capitalized') if capital != 0
  end

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def add_doctor(doc_code)
    doc = Doctor.find_by(code: doc_code)
    return false if doc.nil?
    return false if doctors.include?(doc)
    doc.patients << self
    true
  end

  def add_entry(entry)
    journals << entry
  end

  def proper_email
    at_sign = email.scan(/[\@]/)
    index_at_sign = email =~ /[\@]/
    text_at_end = email.scan(/\@\w+\.\w+/)
    errors.add(:email, 'Missing @ sign') if at_sign.empty?
    errors.add(:email, 'Email needs text before @') if index_at_sign == 0
    errors.add(:email, 'Email needs text after @') if index_at_sign == email.length - 1
    errors.add(:email, 'Email needs text surrounding the . after @') if text_at_end.eql?([])
  end

  def number_comments
    counter = 0
    journals.each do |journal|
      counter += journal.comments.size
    end
    counter
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy, :adddoc, :doctors, :adddoctor, :journals]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  def doctors
    @doctors = @patient.doctors
  end

  def journals
    @journals = @patient.journals
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.password = patient_params[:password]
    respond_to do |format|
      if @patient.save
        session[:patient_id] = @patient.id
        format.html { redirect_to @patient, notice: 'Welcome new patient.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient destroyed.' }
      format.json { head :no_content }
    end
  end

  def adddoc
  end

  def adddoctor
    respond_to do |format|
      if @patient.add_doctor(params[:patient][:doctor][:code])
        format.html { redirect_to @patient, notice: 'Doctor added.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :adddoc }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:name, :email, :password)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/patients/_formd.html.erb
<%= form_for(@patient, :url => "/patients/#{@patient.id}/adddoctor", :method => "patch") do |f| %>
  <%=f.fields_for :doctor do |doc| %>
    <%= doc.label :doctor_code %><br>
    <%= doc.text_field :code %>
  <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Add doctor" %>
  </div>
<% end %>

app/views/patients/adddoc.html.erb
<%= render 'formd' %>

app/views/patients/doctors.html.erb
<h1>Listing <%= current_patient.name %>'s Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @doctors.each do |doctor| %>
    <tr>
      <td><li id='doctors' ><%= doctor.name %></td>
      <td><a id='doctors' ><%= doctor.email %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password hash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.password_hash %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/journals.html.erb
<h1>Listing <%= "#{@patient.name}" %>'s Journals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= link_to "#{journal.name}", patient_journal_path(journal.patient, journal), {:style=>'color:darkcyan;', :class => "css_class"} %></td>
        <td><%= journal.comments.size %></td>
        <% if patient_logged_in? %>
          <td><%= link_to 'Edit', edit_patient_journal_path(journal.patient, journal) %></td>
          <td><%= link_to 'Delete', "/patients/#{journal.patient.id}/journals/#{journal.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if patient_logged_in? %>
  <%= link_to 'Add a new entry', new_patient_journal_path(@patient) %>
<% end %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<% if patient_logged_in? %>
  <a class="banner">Hi <%= current_patient.name %></a> 
<% end %>
<%= simple_format "\n" %>

<strong>Name:</strong>
  <%= @patient.name %>
<%= simple_format "\n" %>

<strong>Email:</strong>
  <%= @patient.email %>
<%= simple_format "\n" %>

<strong>Doctors:</strong>
  <% @patient.doctors.each do |doc| %>
    <%= doc.name %>
  <% end %>
<%= simple_format "\n" %>

<strong>Number of journal entries:</strong>
  <%= @patient.journals.size %>
  <% if doctor_logged_in? && @patient.doctors.include?(current_doctor) %>
    <%= link_to "View #{@patient.name}'s Journal", "/patientsj/#{@patient.id}" %>
  <% end %>
<%= simple_format "\n" %>

<% if current_patient == @patient %>
  <%= link_to 'Add doctor', "/patients/#{@patient.id}/adddoc" %>
  <%= link_to 'Add Entry', new_patient_journal_path(@patient.id) %><br>
<% end %>

</p><br>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path if !doctor_logged_in? %>
<%= link_to 'Back', doctors_path if doctor_logged_in? %>