config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :doctors
  resources :patients do
    resources :journals do
      resources :comments
    end
  end

  root 'welcome#index'
  get '/dlogin' => 'doctor_sessions#new'
  post '/dlogin' => 'doctor_sessions#create'
  get '/dlogout' => 'doctor_sessions#destroy'
  delete '/dlogout' => 'doctor_sessions#destroy'
  get '/plogin' => 'patient_sessions#new'
  post '/plogin' => 'patient_sessions#create'
  get '/plogout' => 'patient_sessions#destroy'
  delete '/plogout' => 'patient_sessions#destroy'
  get '/patients/:id/adddoc' => 'patients#adddoc'
  get '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/add_entry' => 'journals#new'
  get '/deletec' => 'comments#destroy'
  get '/doctors/:id/patients' => 'doctors#patients'
  get '/patients/:id/doctors' => 'patients#doctors'
  patch '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/patientsj/:id' => 'patients#journals'

end

app/models/doctor.rb
# Doctor model
require 'bcrypt'

class Doctor < ActiveRecord::Base
  include BCrypt
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password_hash, presence: true
  validate :name_capital
  validate :proper_email
  validates :code, presence: true
  validates :code, uniqueness: true
  has_many :patients_doctors, dependent: :destroy
  has_many :patients, through: :patients_doctors
  accepts_nested_attributes_for :patients

  def name_capital
    capital = name =~ /[A-Z]/
    errors.add(:name, 'name is not capitalized') if capital != 0
  end

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def proper_email
    at_sign = email.scan(/[\@]/)
    index_at_sign = email =~ /[\@]/
    text_at_end = email.scan(/\@\w+\.\w+/)
    errors.add(:email, 'Missing @ sign') if at_sign.empty?
    errors.add(:email, 'Email needs text before @') if index_at_sign == 0
    errors.add(:email, 'Email needs text after @') if index_at_sign == email.length - 1
    errors.add(:email, 'Email needs text surrounding the . after @') if text_at_end.eql?([])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy, :patients]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  def patients
    @patients = @doctor.patients.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.password = doctor_params[:password]
    respond_to do |format|
      if @doctor.save
        session[:doctor_id] = @doctor.id
        format.html { redirect_to @doctor, notice: 'Welcome new doctor' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def doctor_params
    params.require(:doctor).permit(:name, :email, :password, :code)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :code_to_give_your_patients_to_connect_to_you %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
  
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= link_to "#{doctor.name}", doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/doctors/patients.html.erb
<h1>Listing <%= current_doctor.name %>'s Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of entries</th>
      <th>Number of comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to "#{patient.name}", patient, {:style=>'color:red;', :class => "css_class"} %></td>
        <td><%= patient.journals.size %></td>
        <td><%= patient.number_comments %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<strong>Name:</strong>
  <%= @doctor.name %>
<%= simple_format "\n" %>

<strong>Email:</strong>
  <%= @doctor.email %>
<%= simple_format "\n" %>

<strong>Code:</strong>
  <%= @doctor.code %>
  <%= "(Give this to patients so that they may link their journal to you)" %>
<%= simple_format "\n" %>

<strong>Patients:</strong>
  <%= "No patients yet" if @doctor.patients.empty? %>
  <% @doctor.patients.each do |patient| %>
    <%= link_to "#{patient.name}", patient_path(patient), {:style=>'color:red;', :class => "css_class"} %>
  <% end %>
<%= simple_format "\n" %>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> 