config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :doctors
  resources :patients do
    resources :journals do
      resources :comments
    end
  end

  root 'welcome#index'
  get '/dlogin' => 'doctor_sessions#new'
  post '/dlogin' => 'doctor_sessions#create'
  get '/dlogout' => 'doctor_sessions#destroy'
  delete '/dlogout' => 'doctor_sessions#destroy'
  get '/plogin' => 'patient_sessions#new'
  post '/plogin' => 'patient_sessions#create'
  get '/plogout' => 'patient_sessions#destroy'
  delete '/plogout' => 'patient_sessions#destroy'
  get '/patients/:id/adddoc' => 'patients#adddoc'
  get '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/add_entry' => 'journals#new'
  get '/deletec' => 'comments#destroy'
  get '/doctors/:id/patients' => 'doctors#patients'
  get '/patients/:id/doctors' => 'patients#doctors'
  patch '/patients/:id/adddoctor' => 'patients#adddoctor'
  get '/patientsj/:id' => 'patients#journals'

end

app/models/journal.rb
# Journal model
class Journal < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :body, presence: true
  validates :body, uniqueness: true
  belongs_to :patient
  accepts_nested_attributes_for :patient
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments

  def add_comment(comment_params)
    comments << comment_params
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :set_patient

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
    @patient = @journal.patient
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)
    respond_to do |format|
      if @journal.save
        @patient.add_entry(@journal)
        format.html { redirect_to "/patients/#{@patient.id}/journals/#{@journal.id}", notice: 'Journal created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to patient_journal_path, notice: 'Journal updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to "/patientsj/#{@patient.id}", notice: 'Journal destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_journal
    @journal = Journal.find(params[:id])
  end

  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def journal_params
    params.require(:journal).permit(:name, :body, :patient_id)
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for([@patient, @journal]) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area(:body, size: "50x30") %>
  </div>
  <div class="actions">
    <%= f.submit "Add entry" %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing <%= "#{@patient.name}" %>'s Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', [@patient, @journal] %> |
<%= link_to 'Back to journal', "/patientsj/#{@patient.id}" %>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Journals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.name %></td>
        <td><%= journal.body %></td>
        <td><%= link_to 'Show', patient_journal_path(journal.patient, journal) %></td>
        <td><%= link_to 'Edit', edit_patient_journal_path(journal.patient, journal) %></td>
        <td><%= link_to 'Destroy', "/patients/#{journal.patient.id}/journals/#{journal.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal', new_patient_journal_path %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<strong>Name:</strong>
  <%= @journal.name %>
<%= simple_format "\n" %>

<strong>Body:</strong>
  <%= @journal.body %>
<%= simple_format "\n" %>

<% if !@journal.comments.empty? %>
  <h4>Comments on <%= "\"#{@journal.name}\"" %></h4>
      </tr>
      <% @journal.comments.each do |comment| %>
      <tr>
        <td>
          <li id = 'comments' > <%= comment.content %></a>
        </td>
      <% if doctor_logged_in? %>
        <td><%= link_to "Edit", edit_patient_journal_comment_path(@journal.patient, @journal, comment) %></td>
        <td><%= link_to "Delete", patient_journal_comment_path(@journal.patient, @journal, comment), method: :delete, data: { confirm: "Yes" }  %></td>
      <% end %>
      </tr>
    <% end %>
    </table>
<% else %>
  <%= 'No comments' %>
<% end %>
<%= simple_format "\n" %>

<% if doctor_logged_in? %>
  <%= link_to 'Add comment', new_patient_journal_comment_path(@journal.patient, @journal) %> 
<% end %>

<% if patient_logged_in? %>
  <%= link_to 'Edit', edit_patient_journal_path(@journal.patient, @journal) %> 
<% end %>
<%= simple_format "\n" %>

<%= link_to 'Back', "/patientsj/#{@journal.patient.id}" %>